version: "3"

services:
  traefik:
    image: traefik:v1.7.5-alpine
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme

  website:
    container_name: website
    build:
      context: .
      dockerfile: .docker/app.prod.dockerfile
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    labels:
      - "traefik.enable=true"
      - "traefik.backend=website"
      - "traefik.frontend.rule=Host:janidham.com,www.janidham.com"
