version: "3"

services:
  traefik:
    image: traefik:v1.7.5-alpine
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml

  website:
    container_name: website-dev
    build:
      context: .
      dockerfile: .docker/app.dev.dockerfile
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - "3000:3000"
    labels:
      - "traefik.backend=app-be"
      - "traefik.frontend.rule=Host:app.localhost"
