debug = false

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

  [entryPoints.dashboard]
    address=":8080"

[api]
entrypoint = "dashboard"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "janidham.com"
watch = true
exposedByDefault = false

[acme]
email = "janid.ham20@gmail.com"
storage = "/etc/traefik/acme/acme.json"
entryPoint = "https"
  [acme.httpChallenge]
  entryPoint = "http"

  [[acme.domains]]
    main = "janidham.com"
    sans = ["monitor.janidham.com"]
